#!/bin/bash

PACKAGE_DIR=/var/vcap/packages/portal
JOB_DIR=/var/vcap/jobs/portal
CONF_DIR=$JOB_DIR/config
RUN_DIR=/var/vcap/sys/run/portal
LOG_DIR=/var/vcap/sys/log/portal
PIDFILE=$RUN_DIR/portal.pid
DATA_DIR=/var/vcap/data/portal

export PATH=/var/vcap/packages/ruby_next/bin:$PATH

source /var/vcap/packages/common/utils.sh

case $1 in
  start)
    pid_guard $PIDFILE "portal"

    mkdir -p $RUN_DIR
    mkdir -p $LOG_DIR

    echo $$ > $PIDFILE

    cd $PACKAGE_DIR/portal/
    exec bundle exec thin start --log $LOG_DIR/portal.log \
         >>$LOG_DIR/portal.stdout.log \
         2>>$LOG_DIR/portal.stderr.log

    ;;

  stop)
    kill_and_wait $PIDFILE

    ;;

  *)
    echo "Usage: portal_ctl {start|stop}"

    ;;

esac
