#!/bin/bash


export PATH=/usr/local/rvm/gems/ruby-1.9.3-p484@global/bin:/usr/local/rvm/gems/ruby-1.9.3-p484/bin:/usr/local/rvm/rubies/ruby-1.9.3-p484/bin:/usr/sbin:/usr/bin:/sbin:/bin:$PATH

bundle install --no-deployment --path=./vendor/bundle
bundle exec rake
#bundle exec rspec ./spec/functional/mysql_connection_pool_spec.rb
#bundle exec rspec ./spec/functional/mysql_node_spec.rb:829
#bundle exec rspec ./spec/functional/mysql_backup_job_spec.rb
