source "http://rubygems.org"

gem "nats", "~> 0.4.26"
gem "datamapper", "~> 1.2"
gem "do_sqlite3", "~> 0.10.6", :require => nil
gem "dm-sqlite-adapter", "~> 1.2"
gem "eventmachine", "~> 1.0"
gem "em-http-request", "~> 1.0"
gem "json", "~> 1.6"
gem "uuidtools", "~> 2.1"
gem "ruby-hmac", "~> 0.4.0", :require => "hmac-sha1"
gem "thin", ">= 1.3.1"
gem "sinatra", ">= 0.9.2"
gem "rake", "10.1.0"
gem "curb", "~> 0.7.16"
gem 'vcap_common', :require => ['vcap/common', 'vcap/component'], :git => 'https://github.com/cloudfoundry/vcap-common.git', :ref => '658be8a8f6'
gem 'vcap_logging', :require => ['vcap/logging'], :git => 'https://github.com/cloudfoundry/common.git', :ref => 'b96ec1192'
gem 'vcap_services_base', :git => 'https://github.com/vchs/vcap-services-base.git', :ref => 'cd1278742543'
gem 'vcap_services_messages', :git => 'https://github.com/vchs/vcap-services-messages', :branch => 'f1b09e64f2'

group :test do
  gem "activesupport", "3.2.13"
  gem "sequel", "3.45.0"
  gem "rspec", "2.14.1"
  gem "ci_reporter", "1.9.0"
end
