# Copyright (c) 2009-2011 VMware, Inc.
require 'rspec/core/rake_task'
require 'ci/reporter/rake/rspec'

RSpec::Core::RakeTask.new("spec:integration") do |t|
  t.pattern = [
    'spec/integration/*_spec.rb'
  ]
end

RSpec::Core::RakeTask.new("spec:unit") do |t|
  t.pattern = [
    'spec/unit/*_spec.rb'
  ]
end

desc 'run the integration test'
task :integration => ["spec:integration"]

desc 'run the unit test'
task :default => ["spec:unit"]
