# Copyright (c) 2009-2011 VMware, Inc.
require 'rspec/core/rake_task'
require 'ci/reporter/rake/rspec'

RSpec::Core::RakeTask.new("spec") do |t|
  t.pattern = [
    'spec/unit/*_spec.rb',
    'spec/integration/*_spec.rb'
  ]
end

task :default => :spec
