source 'http://rubygems.org'

gem 'rake'
gem 'eventmachine', '~> 1.0.0'
gem 'cf-message-bus'
gem 'yajl-ruby'

gem 'steno', '~> 1.2.0', :git => 'https://github.com/cloudfoundry/steno.git'
gem 'vcap_common', :git => 'https://github.com/cloudfoundry/vcap-common.git',
  :ref => '658be8a8f6'
gem 'vcap_services_base',
  :git => 'https://github.com/vchs/vcap-services-base.git', :branch => 'master'
gem 'vcap_logging', :require => ['vcap/logging'],
  :git => 'https://github.com/cloudfoundry/common.git', :ref => 'b96ec1192'

group :test do
  gem 'rspec'
end
