source 'http://rubygems.org'

gem 'rake'
gem 'eventmachine', '~> 1.0.0'
gem 'cf-message-bus'
gem 'yajl-ruby'

gem 'steno', '~> 1.2.0', :git => 'git://github.com/cloudfoundry/steno.git'
gem 'vcap_common', :git => 'git://github.com/cloudfoundry/vcap-common.git'

group :test do
  gem 'rspec'
end
