source 'http://rubygems.org'

gem 'rake'
gem 'eventmachine', '~> 1.0.0'
gem 'cf-message-bus'

gem 'steno', '~> 1.2.0', :git => 'https://github.com/cloudfoundry/steno.git'
gem 'vcap_common', :git => 'https://github.com/cloudfoundry/vcap-common.git'
#gem 'vcap_services_messages', :git => 'https://github.com/vchs/vcap-services-messages', :ref => ''
gem 'vcap_services_messages', :path => '/home/eagle/cloudfoundry/vcap-services-messages/'

group :test do
  gem 'rspec'
end
