source "http://rubygems.org"

gem "nats"
gem "datamapper", "~> 1.2"
gem "do_sqlite3", :require => nil
gem "dm-sqlite-adapter", "~> 1.2"
gem "dm-mysql-adapter", "~> 1.2"
gem 'eventmachine'
gem "em-http-request"
gem "json"
gem "mysql2", "~> 0.3.11"
gem "uuidtools"
gem "ruby-hmac", :require => "hmac-sha1"
gem "thin"
gem "sinatra"
gem "rake"
gem "curb"
gem 'vcap_common', :require => ['vcap/common', 'vcap/component'], :git => 'https://github.com/cloudfoundry/vcap-common.git', :ref => '658be8a8f6'
gem 'vcap_logging', :require => ['vcap/logging'], :git => 'https://github.com/cloudfoundry/common.git', :ref => 'b96ec1192'
gem 'vcap_services_base', :git => 'https://github.com/vchs/vcap-services-base.git', :ref => '1035d21136'
gem 'vcap_services_messages', :git => 'https://github.com/vchs/vcap-services-messages', :ref => 'f1b09e64f2'
gem 'warden-client', :require => ['warden/client'], :git => 'https://github.com/cloudfoundry/warden.git', :ref => 'fe6cb51'
gem 'warden-protocol', :require => ['warden/protocol'], :git => 'https://github.com/cloudfoundry/warden.git', :ref => 'fe6cb51'

group :test do
  gem "activesupport", "3.2.13"
  gem "sequel", "3.45.0"
  gem "rspec", "2.14.1"
  gem "ci_reporter", "1.9.0"
end
